### PR TITLE
Rename 'encryptable' to 'encrypts'. Update documentation.

### PR DESCRIPTION
**Pull request by BrandonSurowiec**
To be more in line with Laravel's naming conventions, I propose you rename `$encryptable` to `$encrypts`. Reads a whole lot better and makes it more explicit that we're encrypting those fields.

### CODE REVIEW

**Comment by delatbabel** [comment]
Thanks for the PR.  I'll take a look early next week.  I'm on leave at the moment and since this is not backwards compatible I would have to fix current live projects that would break if I merged this PR immediately.

**Comment by BrandonSurowiec** [comment]
I accidentally didn't realize my newer commits were showing up in this pull request... if you want me to create a pull request for just the initial commit I can do that. Sorry for making your job harder :)

The other two commits were to refactor so we're using Laravel's methods to do the work. That way the package doesn't fall behind when new features appear, but also doesn't create issues when the new functionality is not yet implemented or is not existing on the user's version of Laravel: https://github.com/laravel/framework/commit/b535db45bbc05395b8da7a7447db339d0d0d92f6 

If you could tag your current release, that would help a lot in being able to choose a specific version. I can make it BC if you want by allowing either variable, but I think just tagging it would be good enough.

One last thing. I wanted to add tests, but I didn't get around to it. I'm still new-ish to testing, so it's tricky for me when it requires a Laravel install to test on, since I don't want to mock it all up :)

**Comment by delatbabel** [comment]
Yes, having separate PRs for each change would be easier and better for tracking. Best to create a branch for each change and PR from that branch. When you add commits to a branch they get auto-added to any PR.

Testing traits is always hard -- you almost have to create an entire application and then test cases for that.  Another day maybe.

**Comment by BrandonSurowiec** [comment]
Would you want me to resubmit the first change, but add the ability to use either `encrypts` or the `encryptable` variable for BC?

**Comment by delatbabel** [comment]
Yes that would make sense, thanks.

**Comment by BrandonSurowiec** [comment]
I made a new PR.

**Pull request closed without merging**
